### ISSUE TITLE
Seeing "TypeError: Cannot read property 'Term' of undefined" from sparql.js when running tests.

### ISSUE THREAD

**Issue by pmcb55** [inrupt/solid-sdk-forms#94]
Seems very easy to reproduce - simply checkout the branch `feat/use-lit-vocab-term`, run `npm install && npm test`, i.e.:

```
git clone -b feat/use-lit-vocab-term git@github.com:inrupt/solid-sdk-forms.git
cd solid-sdk-forms
npm install
npm test
```

...and I see...

```
[solid-sdk-forms]$ npm test
> @inrupt/solid-sdk-forms@0.2.0 test /home/pmcb55/tmp/solid-sdk-forms
> jest --coverage
 PASS  test/shex-form-model.test.ts
 FAIL  test/solid-fetch.test.ts
  ● Test suite failed to run
    TypeError: Cannot read property 'Term' of undefined
      at Object.<anonymous> (node_modules/sparqljs/lib/Wildcard.js:1:46)
      at node_modules/sparqljs/lib/SparqlParser.js:694:18
      at Object.<anonymous> (node_modules/sparqljs/lib/SparqlParser.js:1538:3)
 FAIL  test/form-ui.test.ts
  ● Test suite failed to run
    TypeError: Cannot read property 'Term' of undefined
      at Object.<anonymous> (node_modules/sparqljs/lib/Wildcard.js:1:46)
      at node_modules/sparqljs/lib/SparqlParser.js:694:18
      at Object.<anonymous> (node_modules/sparqljs/lib/SparqlParser.js:1538:3)
 FAIL  test/form-model.test.ts
  ● Test suite failed to run
    TypeError: Cannot read property 'Term' of undefined
      at Object.<anonymous> (node_modules/sparqljs/lib/Wildcard.js:1:46)
      at node_modules/sparqljs/lib/SparqlParser.js:694:18
      at Object.<anonymous> (node_modules/sparqljs/lib/SparqlParser.js:1538:3)
```

I updated the `package.json` to all the latest versions (I think), including TypeScript and TypeDoc, so I've no idea what's going on here.

**Comment by RubenVerborgh** [comment]
@joachimvh This seems to be in your part of the code 😉

**Comment by RubenVerborgh** [comment]
@pmcb55 It was found by @joachimvh that this is due to the N3.js version; SPARQL.js is accessing internals that it shouldn't. Will fix there.

**Comment by RubenVerborgh** [comment]
Fixed in `sparqljs@3.0.2`.
